// flow-typed signature: 45fe0f0b875c3d8bf6de233776c64b7c
// flow-typed version: <<STUB>>/babel-plugin-transform-react-require_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-require/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-require/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-require/dist/index'>;
}
