// flow-typed signature: 9ca4636c306bbc769f43a297c2ca16a0
// flow-typed version: <<STUB>>/eslint-config-engagepoint_v^1.0.0-rc.17/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-engagepoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-engagepoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-engagepoint/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/flow-errors' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/lodash' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/redux-saga' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-engagepoint/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-engagepoint/index' {
  declare module.exports: $Exports<'eslint-config-engagepoint'>;
}
declare module 'eslint-config-engagepoint/index.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint'>;
}
declare module 'eslint-config-engagepoint/legacy.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/legacy'>;
}
declare module 'eslint-config-engagepoint/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/best-practices'>;
}
declare module 'eslint-config-engagepoint/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/errors'>;
}
declare module 'eslint-config-engagepoint/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/es6'>;
}
declare module 'eslint-config-engagepoint/rules/flow-errors.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/flow-errors'>;
}
declare module 'eslint-config-engagepoint/rules/flow.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/flow'>;
}
declare module 'eslint-config-engagepoint/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/imports'>;
}
declare module 'eslint-config-engagepoint/rules/lodash.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/lodash'>;
}
declare module 'eslint-config-engagepoint/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/react'>;
}
declare module 'eslint-config-engagepoint/rules/redux-saga.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/redux-saga'>;
}
declare module 'eslint-config-engagepoint/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/style'>;
}
declare module 'eslint-config-engagepoint/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/rules/variables'>;
}
declare module 'eslint-config-engagepoint/server.js' {
  declare module.exports: $Exports<'eslint-config-engagepoint/server'>;
}
